### ISSUE TITLE
http://cononrails.itasca.net/events/new is broken

### ISSUE THREAD

**Issue by davedujour** [ConOnRails/ConOnRails#103] opened 2021-04-17 02:00 UTC
via both the Log New Event button on the Main tab and the Log Event tab itself.

**Comment by mshappe** [comment] 2021-06-12 23:27
Cannot reproduce. Closing.

**Closed by mshappe** 2021-06-12 23:27 UTC

**Comment by wmamurphy** [comment] 2021-07-13 00:53
Appears to be working now.  Perhaps fixed by something else?
